# Generated by Django 2.1.3 on 2019-08-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarroLojaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_carro', models.CharField(max_length=100)),
                ('placa_carro', models.CharField(max_length=100)),
                ('vlr_finan', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cor_carro', models.CharField(max_length=100)),
                ('cidade_loja', models.CharField(max_length=100)),
                ('uf_loja', models.CharField(max_length=100)),
                ('nome_loja', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SimulaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.IntegerField()),
                ('dt_nasc', models.DateField()),
                ('celular', models.IntegerField()),
                ('ocupacao', models.CharField(max_length=100)),
                ('cep', models.IntegerField()),
                ('renda_mensal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('renda_comple', models.BooleanField()),
                ('tipo_rend', models.CharField(max_length=100)),
                ('vlr_renda', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vlr_finan', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vlr_entra', models.DecimalField(decimal_places=2, max_digits=6)),
                ('qtd_parcela', models.IntegerField()),
                ('tx_cet_aa', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tx_cet_mm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('iof', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tarifa_cad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('registro_ctt', models.DecimalField(decimal_places=2, max_digits=6)),
                ('retorno', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tarifa_aval', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vlr_finan_fim', models.DecimalField(decimal_places=2, max_digits=6)),
                ('img_placa', models.ImageField(upload_to='img_placa')),
                ('num_placa', models.CharField(max_length=100)),
            ],
        ),
    ]
