# Generated by Django 2.1.3 on 2019-08-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarroApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('cor', models.IntegerField()),
                ('ano', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LojaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cidade_loja', models.CharField(max_length=100)),
                ('uf_loja', models.CharField(max_length=100)),
                ('nome_loja', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='carrolojamodel',
            name='cidade_loja',
        ),
        migrations.RemoveField(
            model_name='carrolojamodel',
            name='nome_loja',
        ),
        migrations.RemoveField(
            model_name='carrolojamodel',
            name='uf_loja',
        ),
        migrations.AddField(
            model_name='carrolojamodel',
            name='fk_loja',
            field=models.IntegerField(default=int),
            preserve_default=False,
        ),
    ]
