# Generated by Django 2.1.3 on 2019-08-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190818_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulamodel',
            name='celular',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='simulamodel',
            name='cep',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='simulamodel',
            name='cpf',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='simulamodel',
            name='dt_nasc',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='simulamodel',
            name='img_placa',
            field=models.ImageField(null=True, upload_to='img_placa'),
        ),
        migrations.AlterField(
            model_name='simulamodel',
            name='iof',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='simulamodel',
            name='ocupacao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='simulamodel',
            name='qtd_parcela',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='simulamodel',
            name='registro_ctt',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='simulamodel',
            name='renda_comple',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='simulamodel',
            name='renda_mensal',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='simulamodel',
            name='retorno',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='simulamodel',
            name='tarifa_aval',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='simulamodel',
            name='tarifa_cad',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='simulamodel',
            name='tipo_rend',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='simulamodel',
            name='tx_cet_aa',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='simulamodel',
            name='tx_cet_mm',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='simulamodel',
            name='vlr_entra',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='simulamodel',
            name='vlr_finan',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='simulamodel',
            name='vlr_finan_fim',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='simulamodel',
            name='vlr_renda',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
