# Generated by Django 2.1.3 on 2019-08-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190818_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carroapi',
            name='cor',
            field=models.CharField(max_length=100),
        ),
    ]
